---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodgate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: woodgate
  values:
    controllers:
      woodgate:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/woodgate
              tag: 2.3.2@sha256:ff2e3f7974e40b2d3921e38a7518c968f37bba47183c201f3fa774a5938e98d4
            env:
              TZ: Australia/Melbourne
              WOODGATE_ENTRA_SYNC_INTERVAL: 24h
              WOODGATE_ENTRA_TRANSITIVE_GROUPS: true
              WOODGATE_HTTP_CLIENT_IP_SOURCE: xff_trusted_cidrs
              WOODGATE_HTTP_CLIENT_IP_TRUSTED_CIDRS: 10.42.0.0/16
              WOODGATE_STORAGE_KIND: file
              WOODGATE_STORAGE_FILE_ROOT: /media
              WOODGATE_URL: https://{{ .Release.Name }}.woodleighschool.net
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.woodleighschool.net"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      media:
        existingClaim: "{{ .Release.Name }}-media"
      tmp:
        type: emptyDir
