---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jamf-user-sync
spec:
  chartRef:
    kind: OCIRepository
    name: jamf-user-sync
  interval: 1h
  values:
    controllers:
      jamf-user-sync:
        type: cronjob
        cronjob:
          schedule: "@daily"
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          timeZone: "Australia/Melbourne"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/jamf-user-sync
              tag: 3.0.1@sha256:fa23f542bfe76ee281a040363e7b565446cca17b583500121ff721cdbb52a334
            env:
              JAMF_HOST: wdm.jamfcloud.com
              LDAP_HOST: wdc01.woodleighschool.net
              TZ: Australia/Melbourne
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
