---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jamf-recovery-lock
spec:
  chartRef:
    kind: OCIRepository
    name: jamf-recovery-lock
  interval: 1h
  values:
    controllers:
      jamf-recovery-lock:
        type: cronjob
        cronjob:
          schedule: "@daily"
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          timeZone: "Australia/Melbourne"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/jamf-recovery-lock
              tag: 3.1.0@sha256:069ded0c1c8d7b27d754422dddd3b13edaa93f049df6e4c647713e40c59c5f41
            env:
              PASSWORD_LENGTH: 10
              LOG_LEVEL: debug
              INSTANCE_DOMAIN: wdm.jamfcloud.com
              TZ: Australia/Melbourne
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      tmp:
        type: emptyDir
