---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodstar
spec:
  chartRef:
    kind: OCIRepository
    name: woodstar
  interval: 1h
  values:
    controllers:
      woodstar:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/woodstar
              tag: 0.11.0@sha256:3dcde03baa84e4a4168f90c61d307e8df11fd6946d28f9c0cbbc4ef2b930f304
            env:
              TZ: Australia/Melbourne
              WOODSTAR_ENTRA_TRANSITIVE_GROUPS: true
              WOODSTAR_HTTP_CLIENT_IP_SOURCE: xff_trusted_cidrs
              WOODSTAR_HTTP_CLIENT_IP_TRUSTED_CIDRS: 10.42.0.0/16
              WOODSTAR_ORBIT_SCRIPT_EXECUTION_TIMEOUT: 10m
              WOODSTAR_STORAGE_KIND: s3
              WOODSTAR_STORAGE_S3_BUCKET: woodstar
              WOODSTAR_STORAGE_S3_ENDPOINT: https://67ccf561cd3d68abc81838e145a046b8.r2.cloudflarestorage.com
              WOODSTAR_STORAGE_S3_PATH_STYLE: "true"
              WOODSTAR_STORAGE_S3_REGION: auto
              WOODSTAR_URL: "https://{{ .Release.Name }}.woodleigh.vic.edu.au"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.woodleigh.vic.edu.au"
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      tmp:
        type: emptyDir
